title:              ANSE Data Services
email:              albareydata@gmail.com
description:        Website about Data Science - Clean Blog Theme by Start Bootstrap - 10/29/2022 10:48 PM
author:             author Albarey Data Services
baseurl:            ""
url:                #"https://albarey33.github.io"   # Disabled changing repos

# Social Profiles
twitter_username:   
github_username:    albarey33
facebook_username:    
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge

